# Generated by Django 5.2.5 on 2025-08-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='active_until',
            field=models.DateTimeField(null=True),
        ),
    ]
